# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MCDM
                                 A QGIS plugin
 This plugin allows you to utilize MCDM techniques to classify areas for different suitability classes
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-10
        copyright            : (C) 2024 by tolga.evcimen
        email                : h.tolgaevcimen@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import sys
import os

sys.path.insert(0, str(os.path.join(os.path.dirname(os.path.realpath(__file__)), ''))+'Lib\site-packages')

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MCDM class from file MCDM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mcdm_ahp import MCDM
    return MCDM(iface)
